on: [push]

jobs:
  regex_test:
    runs-on: ubuntu-latest
    name: Test
    steps:
    - name: Get dotnet core
      id: hello
      uses: actions/setup-dotnet@v1
    - name: Run tests for all regular expressions
      run: dotnet test