on: [push]

jobs:
  regex_test:
    runs-on: ubuntu-latest
    name: Test
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install dotnet Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
    - name: Run tests for all regular expressions
      run: dotnet test
  test_golang:
    runs-on: ubuntu-latest
    name: Test Go
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install Go
      uses: actions/setup-go@v1
    - name: install go liberary
      run: go get github.com/dlclark/regexp2/...
    - name: Run tests for all regular expressions
      run: go run Go/RegexMaze.go
